name: Deployment workflow
on:
  push:

jobs:
  cdk:
    name: Check template
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_CONTENT_BUCKET: ${{ secrets.AWS_CONTENT_BUCKET }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - run: cd deploy
      - name: Restore dependencies
        run: npm install
      - run: ls .
      - run: ls ./node_modules
      - run: ls ./node_modules/aws-cdk/
      - run: ls ./node_modules/aws-cdk/bin/
      - name: Synth template
        run: ./node_modules/aws-cdk/bin/cdk synth --path-metadata false --version-reporting false
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_CONTENT_BUCKET: ${{ secrets.AWS_CONTENT_BUCKET }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Upload content artifact
        uses: actions/upload-artifact@v2
        with:
          name: content
          path: content/*.md
      - run: cd deploy
      - name: Restore dependencies
        run: npm install
      - name: Run deployment
        run: ./node_modules/aws-cdk/bin/cdk deploy