name: Deployment workflow
on:
  push:

jobs:
  synth:
    name: Check template
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_CONTENT_BUCKET: ${{ secrets.AWS_CONTENT_BUCKET }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Synth template
        run: cd deploy && npm install && ./node_modules/aws-cdk/bin/cdk synth --path-metadata false --version-reporting false
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-20.04
    needs: synth
    if: github.ref == 'refs/heads/main'
    env:
      AWS_CONTENT_BUCKET: ${{ secrets.AWS_CONTENT_BUCKET }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Upload content artifact
        uses: actions/upload-artifact@v2
        with:
          name: content
          path: content/*.md
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run deployment
        run: cd deploy && npm install && ./node_modules/aws-cdk/bin/cdk deploy --require-approval never