name: Deploy content
on:
  push:

jobs:
  package:
    name: Package up content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: content
          path: content/*.md
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: package
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_CONTENT_BUCKET: ${{ secrets.AWS_CONTENT_BUCKET }}
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: content
    - name: Run deployment playbook
      uses: ./.github/actions/ansible-playbook
      with:
        playbook: deploy/deploy.yml